import PushNotificationIOS from '@react-native-community/push-notification-ios';
import {Client, XMTPPush} from '@xmtp/react-native-sdk';
import RNPush from 'react-native-push-notification';
import {SupportedContentTypes} from '../consts/ContentTypes';
import {
  CHANNEL_ID,
  CHANNEL_NAME,
  PUSH_SERVER,
} from '../consts/PushNotifications';

export class PushNotificatons {
  client: Client<SupportedContentTypes>;
  constructor(client: Client<SupportedContentTypes>) {
    this.client = client;
    this.configure();
  }
  configure = () => {
    const client = this.client;
    RNPush.configure({
      async onRegister(registrationData) {
        try {
          const token = registrationData.token;
          console.log('PUSH NOTIFICATION TOKEN:', token);
          XMTPPush.register(PUSH_SERVER, token);
          await client.contacts.refreshConsentList();
          const conversations = await client.conversations.listGroups();
          const pushClient = new XMTPPush(client);
          pushClient.subscribe(conversations.map(c => c.topic));
          for (const conversation of conversations) {
            RNPush.createChannel(
              {
                channelId: CHANNEL_ID + conversation.topic, // (required)
                channelName: CHANNEL_NAME + conversation.topic, // (required)
              },
              created =>
                console.log(
                  `PUSH NOTIFICATION createChannel returned '${created}'`,
                ),
            );
          }
          console.log('PUSH NOTIFICATION Registered push token:', token);
        } catch (error) {
          console.error(
            'PUSH NOTIFICATION Failed to register push token:',
            error,
          );
        }
      },
      onRegistrationError(error) {
        console.log('PUSH NOTIFICATION Failed to register push token:', error);
      },
      onAction(notification) {
        console.log('PUSH NOTIFICATION ACTION:', notification.action);
      },
      onRemoteFetch(notification) {
        console.log('PUSH NOTIFICATION REMOTE FETCH:', notification);
      },
      onNotification(notification) {
        console.log('PUSH NOTIFICATION NOTIFICATION:', notification);
        const encryptedMessage = notification.data.encryptedMessage;
        const topic = notification.data.topic;

        if (encryptedMessage == null || topic == null) {
          return;
        }
        // (async () => {
        //   const conversations = await client.conversations.list();
        //   const conversation = conversations.find(
        //     (c: {topic: string}) => c.topic === topic,
        //   );
        //   if (conversation == null) {
        //     return;
        //   }

        //   const peerAddress = conversation.peerAddress;
        //   const decodedMessage = await conversation.decodeMessage(
        //     encryptedMessage,
        //   );
        //   const body = decodedMessage.content;

        //   PushNotification.localNotification({
        //     /* Android Only Properties */
        //     channelId: 'xmtp-react-native-example-dm', // (required) channelId, if the channel doesn't exist, notification will not trigger.
        //     messageId: 'google:message_id', // (optional) added as `message_id` to intent extras so opening push notification can find data stored by @react-native-firebase/messaging module.

        //     /* iOS only properties */
        //     category: '', // (optional) default: empty string
        //     subtitle: 'My Notification Subtitle', // (optional) smaller title below notification title

        //     /* iOS and Android properties */
        //     id: 0, // (optional) Valid unique 32 bit integer specified as string. default: Autogenerated Unique ID
        //     title: peerAddress, // (optional)
        //     message: body, // (required)
        //   });
        // })().catch(console.error);

        // process the notification here
        // required on iOS only
        notification.finish(PushNotificationIOS?.FetchResult.NoData);
      },

      // Android only
      // senderID: 'YOUR_FIREBASE_SENDER_ID',
      // iOS only
      permissions: {
        alert: true,
        badge: true,
        sound: true,
      },
      popInitialNotification: true,
      requestPermissions: true,
    });
  };
}
