name: iOS Tests
on:
  pull_request:
    paths:
      - 'ios/**'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up Xcode
        uses: actions/setup-xcode@v1
        with:
          xcode-version: '15.0.1'
      - uses: actions/setup-node@v3
      - run: yarn
      - name: Build iOS App
        run: yarn ios --no-packager --mode Release
