name: iOS Tests
on:
  pull_request:
    paths:
      - 'ios/**'
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Select Xcode 12.4
        run: sudo xcode-select -switch /Applications/Xcode_15.0.1.app # Switch Xcode version
      - uses: actions/setup-node@v3
      - run: yarn
      - name: Build iOS App
        run: yarn ios --no-packager --mode Release
