name: Release
on:
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
      - uses: actions/setup-node@v3
      - run: yarn
      - run: cd android && ./gradlew assembleRelease
      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: APK
          path: ./android/app/build/outputs/apk/release/app-release.apk
